### ISSUE TITLE
the formula to calculate AP

### ISSUE THREAD

**Issue by captainst** [flcello/MultiStar#1]
First of all, multistar is a brilliant idea targeting the tissue overlapping issues. Congrats!

Para.3.1 Evaluation metrics, the author shows an average precision AP = TP/(TP+FP+FN). This is quite different from the ordinary AP formula, as the area under the PR curve.

Is there a reference to this average precision calculation? Many thanks.

**Comment by flcello** [comment]
Thanks for the comment and the question!

Since we extended the existing method [StarDist](https://github.com/stardist/stardist), we tried to use a similar metric as in the original publication. They describe their metric in section 3.2 of their [paper](https://arxiv.org/pdf/1806.03535.pdf). I hope this helps!

**Comment by captainst** [comment]
Thank you very much! I'll check stardist paper.
